spring.application.name=askmydoc
server.port=8000
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.chat.options.max-output-tokens=2048
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=askmydoc
spring.ai.vectorstore.mongodb.collection-name=chunks
spring.servlet.multipart.max-file-size=10MB
cohere.api.key=${COHERE_API_KEY}



